In [1]:
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np

In [2]:
df_regression = pd.read_csv('./code_generated_csv/df_regression_cleaned.csv',index_col = 0)
df_regression[:212]

,time,highorlow,wave5,wave9,downpinbar,uppinbar,toptype,bottomtype,downpregnanttype,uppregnanttype,downswallowtype,upswallowtype,RSIlessthan,RSImorethan,topdivergence,bottomdivergence,RSIShortgodown,RSIShortgoup
0,2020-01-02 04:15:00,0,0.000000,0.000000,0,0,0,1,1,1,0,1,0.000000,76.665264,0,0,1,1
4,2020-01-02 04:30:00,0,0.000000,0.000000,0,0,0,0,0,0,0,1,0.000000,78.477517,0,0,1,0
8,2020-01-02 04:45:00,0,0.000000,0.000000,0,0,0,0,0,0,0,1,72.420456,0.000000,0,0,1,0
9,2020-01-02 05:00:00,0,0.000000,0.000000,0,0,1,0,0,0,0,0,66.862869,0.000000,0,0,0,0
10,2020-01-02 05:15:00,0,0.000000,0.000000,0,0,1,0,0,0,0,0,61.175160,0.000000,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,2020-01-09 22:45:00,0,0.000000,0.000000,0,0,0,0,0,0,0,0,0.000000,0.000000,0,0,1,1
422,2020-01-09 23:00:00,0,0.000000,0.000000,0,0,0,0,0,0,0,0,62.460026,0.000000,0,0,0,1
423,2020-01-09 23:15:00,0,0.000000,0.000000,0,0,0,0,0,0,0,1,0.000000,66.552762,0,0,0,1
424,2020-01-09 23:45:00,0,0.000000,0.000000,0,0,0,0,0,0,0,1,0.000000,69.195751,0,0,1,0
432,2020-01-10 00:00:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.000000,71.681685,1,0,1,0

In [3]:
df_regression['RSIlessthan'] = df_regression['RSIlessthan']/100
df_regression['RSImorethan'] = df_regression['RSImorethan']/100

In [4]:
# df_regression['downpinbar'] = df_regression['downpinbar']/10
# df_regression['uppinbar'] = df_regression['uppinbar']/10

In [5]:
df_regression = df_regression[212:]

In [6]:
df_long_regression = df_regression[(df_regression.highorlow == 1) | (df_regression.highorlow == 0)]

In [7]:
df_long_regression[df_long_regression.time<= '2020-12-01']

,time,highorlow,wave5,wave9,downpinbar,uppinbar,toptype,bottomtype,downpregnanttype,uppregnanttype,downswallowtype,upswallowtype,RSIlessthan,RSImorethan,topdivergence,bottomdivergence,RSIShortgodown,RSIShortgoup
436,2020-01-10 10:15:00,0,-1.187331,-1.242581,0,0,0,0,0,0,0,0,0.242383,0.000000,1,0,0,0
440,2020-01-10 10:30:00,0,-1.125970,-1.159000,0,0,0,0,0,0,0,0,0.222634,0.000000,1,0,0,0
444,2020-01-10 10:45:00,0,-1.085477,-1.105343,0,0,0,0,0,0,0,0,0.212682,0.000000,1,0,0,1
448,2020-01-10 11:00:00,0,-0.977252,-0.967156,0,0,0,0,0,0,0,0,0.192942,0.000000,1,0,0,1
449,2020-01-10 11:15:00,0,-0.977252,-0.967156,0,0,0,1,0,0,0,0,0.000000,0.310503,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37654,2020-11-30 21:00:00,0,1.101966,1.619118,0,0,0,0,0,0,0,0,0.000000,0.706843,0,1,1,1
37656,2020-11-30 21:15:00,0,1.146746,1.670258,0,0,0,0,0,0,0,0,0.000000,0.723446,0,1,1,0
37657,2020-11-30 21:30:00,0,1.146746,1.670258,0,1,0,0,0,0,0,0,0.000000,0.726779,0,1,1,0
37658,2020-11-30 21:45:00,0,1.146746,1.670258,0,0,0,0,0,0,1,0,0.668237,0.000000,0,1,0,0
37659,2020-11-30 22:00:00,0,1.146746,1.670258,0,0,0,0,0,0,1,0,0.000000,0.678564,0,1,0,0

In [8]:
len(df_long_regression)

11757

In [9]:
df_short_regression = df_regression[(df_regression.highorlow == -1) | (df_regression.highorlow == 0)]
df_short_regression

,time,highorlow,wave5,wave9,downpinbar,uppinbar,toptype,bottomtype,downpregnanttype,uppregnanttype,downswallowtype,upswallowtype,RSIlessthan,RSImorethan,topdivergence,bottomdivergence,RSIShortgodown,RSIShortgoup
433,2020-01-10 00:15:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.682902,0.000000,1,0,1,0
434,2020-01-10 00:30:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.592357,0.000000,1,0,0,0
435,2020-01-10 00:45:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.000000,0.606407,1,0,0,0
436,2020-01-10 10:15:00,0,-1.187331,-1.242581,0,0,0,0,0,0,0,0,0.242383,0.000000,1,0,0,0
440,2020-01-10 10:30:00,0,-1.125970,-1.159000,0,0,0,0,0,0,0,0,0.222634,0.000000,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39139,2020-12-23 17:00:00,0,-1.326742,-1.263463,0,0,0,0,0,1,0,0,0.466682,0.000000,1,0,0,0
39140,2020-12-24 10:45:00,0,-1.323576,-1.257792,0,1,0,0,0,0,0,0,0.371417,0.000000,1,0,0,1
39144,2020-12-24 11:00:00,0,-1.280754,-1.182340,0,1,0,0,0,0,0,0,0.000000,0.393343,1,0,0,1
39145,2020-12-24 11:15:00,0,-1.280754,-1.182340,0,0,0,0,0,0,0,0,0.000000,0.425702,1,0,0,1
39146,2020-12-24 11:30:00,0,-1.280754,-1.182340,0,0,0,0,0,0,0,0,0.000000,0.472811,1,0,0,0

In [10]:
df_short_regression[df_short_regression.time<= '2020-12-01']

,time,highorlow,wave5,wave9,downpinbar,uppinbar,toptype,bottomtype,downpregnanttype,uppregnanttype,downswallowtype,upswallowtype,RSIlessthan,RSImorethan,topdivergence,bottomdivergence,RSIShortgodown,RSIShortgoup
433,2020-01-10 00:15:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.682902,0.000000,1,0,1,0
434,2020-01-10 00:30:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.592357,0.000000,1,0,0,0
435,2020-01-10 00:45:00,-1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.000000,0.606407,1,0,0,0
436,2020-01-10 10:15:00,0,-1.187331,-1.242581,0,0,0,0,0,0,0,0,0.242383,0.000000,1,0,0,0
440,2020-01-10 10:30:00,0,-1.125970,-1.159000,0,0,0,0,0,0,0,0,0.222634,0.000000,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37654,2020-11-30 21:00:00,0,1.101966,1.619118,0,0,0,0,0,0,0,0,0.000000,0.706843,0,1,1,1
37656,2020-11-30 21:15:00,0,1.146746,1.670258,0,0,0,0,0,0,0,0,0.000000,0.723446,0,1,1,0
37657,2020-11-30 21:30:00,0,1.146746,1.670258,0,1,0,0,0,0,0,0,0.000000,0.726779,0,1,1,0
37658,2020-11-30 21:45:00,0,1.146746,1.670258,0,0,0,0,0,0,1,0,0.668237,0.000000,0,1,0,0
37659,2020-11-30 22:00:00,0,1.146746,1.670258,0,0,0,0,0,0,1,0,0.000000,0.678564,0,1,0,0

In [11]:
df_short_regression['highorlow'] = [1 if df_short_regression.highorlow.iloc[i] == -1 else 0 for i in range(len(df_short_regression))]

<ipython-input-11-de0c41055cc1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_short_regression['highorlow'] = [1 if df_short_regression.highorlow.iloc[i] == -1 else 0 for i in range(len(df_short_regression))]

In [12]:
df_short_regression

,time,highorlow,wave5,wave9,downpinbar,uppinbar,toptype,bottomtype,downpregnanttype,uppregnanttype,downswallowtype,upswallowtype,RSIlessthan,RSImorethan,topdivergence,bottomdivergence,RSIShortgodown,RSIShortgoup
433,2020-01-10 00:15:00,1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.682902,0.000000,1,0,1,0
434,2020-01-10 00:30:00,1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.592357,0.000000,1,0,0,0
435,2020-01-10 00:45:00,1,1.894557,1.768007,0,0,0,0,0,0,0,0,0.000000,0.606407,1,0,0,0
436,2020-01-10 10:15:00,0,-1.187331,-1.242581,0,0,0,0,0,0,0,0,0.242383,0.000000,1,0,0,0
440,2020-01-10 10:30:00,0,-1.125970,-1.159000,0,0,0,0,0,0,0,0,0.222634,0.000000,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39139,2020-12-23 17:00:00,0,-1.326742,-1.263463,0,0,0,0,0,1,0,0,0.466682,0.000000,1,0,0,0
39140,2020-12-24 10:45:00,0,-1.323576,-1.257792,0,1,0,0,0,0,0,0,0.371417,0.000000,1,0,0,1
39144,2020-12-24 11:00:00,0,-1.280754,-1.182340,0,1,0,0,0,0,0,0,0.000000,0.393343,1,0,0,1
39145,2020-12-24 11:15:00,0,-1.280754,-1.182340,0,0,0,0,0,0,0,0,0.000000,0.425702,1,0,0,1
39146,2020-12-24 11:30:00,0,-1.280754,-1.182340,0,0,0,0,0,0,0,0,0.000000,0.472811,1,0,0,0

In [13]:
# import matplotlib.pyplot as plt

In [14]:
# plt.hist(df_long_regression.wave5)

In [15]:
# len(df_long_regression.uppregnanttype)

In [16]:
# plt.hist()

In [17]:
# #logistic regression代码
# #train_cols = df_regression[['wave5','wave9','downpinbar','toptype','downpregnanttype','downswallowtype','RSIlessthan','topdivergence','RSIShortgodown']]
# train_cols = df_long_regression[['wave5','wave9','uppinbar','bottomtype','uppregnanttype','upswallowtype','RSImorethan','bottomdivergence','RSIShortgoup']]
# # Index([gre, gpa, prestige_2, prestige_3, prestige_4], dtype=object)
# logit = sm.Logit(df_long_regression['highorlow'], train_cols)
# #sm.OLS(data.endog, data.exog).fit()
# # 拟合模型
# result = logit.fit()

In [18]:
# result.conf_int()

In [19]:
# result.summary()

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
columns = ['wave5','wave9','uppinbar','bottomtype','uppregnanttype','upswallowtype','RSImorethan','bottomdivergence','RSIShortgoup']
X = df_long_regression[columns]

In [22]:
X.index

Int64Index([  436,   440,   444,   448,   449,   450,   451,   456,   457,
              458,
            ...
            39121, 39132, 39136, 39137, 39138, 39139, 39140, 39144, 39145,
            39146],
           dtype='int64', length=11757)

In [23]:
columns1 = ['wave5','wave9','downpinbar','toptype','downpregnanttype','downswallowtype','RSIlessthan','topdivergence','RSIShortgodown']
X1 = df_short_regression[columns1]

In [24]:
y = df_long_regression['highorlow']

In [25]:
y1 = df_short_regression['highorlow']

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [27]:
# from sklearn.metrics import classification_report, confusion_matrix
# from sklearn.linear_model import LogisticRegression
# lr = LogisticRegression()
# # from sklearn.model_selection import train_test_split
# # X_train, X_test, y_train, y_test = train_test_split(X, y)
# X_train, X_test, y_train, y_test = X[:int(np.round(len(df_long_regression)*0.7))],X[int(np.round(len(df_long_regression)*0.7)):],y[:int(np.round(len(df_long_regression)*0.7))],y[int(np.round(len(df_long_regression)*0.7)):]
# lr.fit(X_train, y_train)
# LogisticRegression()
# y_pred = lr.predict(X_test)
# print('lr predict:\n', classification_report(y_test, y_pred=y_pred))

In [28]:
lr = LogisticRegression()
X_train, X_test, y_train, y_test = X[X.index <= 37659],X[X.index > 37659],y[y.index <= 37659],y[y.index > 37659]
lr.fit(X_train, y_train)
LogisticRegression()
y_pred = lr.predict(X_test)
print('lr predict:\n', classification_report(y_test, y_pred=y_pred))

lr predict:
               precision    recall  f1-score   support

           0       0.91      0.98      0.94       549
           1       0.61      0.24      0.34        72

    accuracy                           0.89       621
   macro avg       0.76      0.61      0.64       621
weighted avg       0.87      0.89      0.87       621

In [29]:
lr.coef_

array([[ 0.05843689, -0.0647898 ,  0.6670569 ,  0.25799314, -0.12518622,
         0.23277769, -0.44213136,  1.02502012,  1.69279588]])

In [30]:
lr1 = LogisticRegression()
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y)
X1_train, X1_test, y1_train, y1_test = X1[X1.index <= 37659],X1[X1.index > 37659],y1[y1.index <= 37659],y1[y1.index > 37659]
lr1.fit(X1_train, y1_train)
LogisticRegression()
y1_pred = lr1.predict(X1_test)
print('lr1 predict:\n', classification_report(y1_test, y_pred=y1_pred))

lr1 predict:
               precision    recall  f1-score   support

           0       0.90      0.96      0.93       549
           1       0.50      0.26      0.34        78

    accuracy                           0.88       627
   macro avg       0.70      0.61      0.64       627
weighted avg       0.85      0.88      0.86       627

In [31]:
cnf = confusion_matrix(y_test, y_pred, labels=y_test.unique())
print(f'confusion_matrix {y_test.shape}: \n', cnf)

confusion_matrix (621,):
 [[538  11]
 [ 55  17]]

In [32]:
cnf1 = confusion_matrix(y1_test, y1_pred, labels=y1_test.unique())
print(f'confusion_matrix {y1_test.shape}: \n', cnf1)

confusion_matrix (627,):
 [[529  20]
 [ 58  20]]

In [33]:
lr.coef_

array([[ 0.05843689, -0.0647898 ,  0.6670569 ,  0.25799314, -0.12518622,
         0.23277769, -0.44213136,  1.02502012,  1.69279588]])

In [34]:
lr1.coef_

array([[-0.26167219,  0.30302861,  0.82244435,  0.08690347, -0.13321442,
        -0.12782366,  0.98253172,  1.52658917,  1.32024286]])

In [35]:
r = pd.DataFrame(lr.coef_,columns = columns)
r

,wave5,wave9,uppinbar,bottomtype,uppregnanttype,upswallowtype,RSImorethan,bottomdivergence,RSIShortgoup
0,0.058437,-0.06479,0.667057,0.257993,-0.125186,0.232778,-0.442131,1.02502,1.692796

In [36]:
r1 = pd.DataFrame(lr1.coef_,columns = columns1)
r1

,wave5,wave9,downpinbar,toptype,downpregnanttype,downswallowtype,RSIlessthan,topdivergence,RSIShortgodown
0,-0.261672,0.303029,0.822444,0.086903,-0.133214,-0.127824,0.982532,1.526589,1.320243