In [1]:
import pandas as pd
import numpy as np
from dataProcess.DataClean import CDataClean
import matplotlib.pyplot as plt

In [2]:
# from dataProcess.DataClean import CDataClean
# CDC = CDataClean('/Users/Administrator/Desktop/pythonHistoricalTesting/data/USA30.IDXUSD_Candlestick_15_M_BID_15.04.2018-20.11.2020.csv')
# df_c = CDC.TranslateCsvToDF_NotDropDuplicates()
# SCData = pd.read_csv(r'C:\Users\Administrator\Desktop\pythonHistoricalTesting\code_generated_csv\df_15min_combine_to_day.csv',index_col = 0)
# SCData[:5]
SCData = pd.read_csv('C:/Users/Administrator/Desktop/pythonHistoricalTesting/data/SCData/YMH21-CBOT.scid_BarData_15min.txt',parse_dates = {'Time' : [0,1]})
SCData.columns = ['Time','Open','High','Low','Close','Volume','NumberOfTrades','BidVolume','AskVolume']

In [3]:
Analysis_Data = SCData.loc[(SCData.Time >= '2019-01-01') & (SCData.Time <= '2020-12-25') & (SCData.Volume >= 10000)].reset_index(drop = True)#剔除没有交易的周六？
Analysis_Data.head(10)

,Time,Open,High,Low,Close,Volume,NumberOfTrades,BidVolume,AskVolume
0,2019-01-02 08:30:00,22913,22998,22893,22993,17427,15543,8749,8678
1,2019-01-02 08:45:00,22994,23066,22992,23039,13398,11971,6484,6914
2,2019-01-02 09:00:00,23038,23173,22981,23155,13816,12027,7040,6776
3,2019-01-02 09:15:00,23157,23174,23087,23096,10712,9629,5457,5255
4,2019-01-02 09:45:00,23166,23224,23129,23189,10597,9088,5315,5282
5,2019-01-02 10:15:00,23268,23320,23231,23241,12992,11000,6704,6288
6,2019-01-02 10:30:00,23242,23291,23198,23282,10351,8995,5245,5106
7,2019-01-03 08:30:00,23106,23121,22956,22999,19021,17202,9465,9556
8,2019-01-03 08:45:00,23000,23008,22931,22998,11304,10107,5700,5604
9,2019-01-03 09:00:00,22997,22997,22762,22769,18691,16489,9763,8928

In [4]:
Analysis_Data.Open = [float(x) for x in Analysis_Data.Open]
Analysis_Data.High = [float(x) for x in Analysis_Data.High]
Analysis_Data.Low  = [float(x) for x in Analysis_Data.Low]
Analysis_Data.Close  = [float(x) for x in Analysis_Data.Close]
Analysis_Data.Volume  = [float(x) for x in Analysis_Data.Volume]

In [5]:
from features.Bars import *
from features.Technics import *
Analysis_Data = IdentifyRsi(Analysis_Data)
Analysis_Data = IdentifyPinBar(Analysis_Data)
Analysis_Data = IdentifyTopBottomType(Analysis_Data)
Analysis_Data = IdentifyPregnantType(Analysis_Data)
Analysis_Data = IdentifyTriplePregnantType(Analysis_Data)
Analysis_Data = IdentifySwallowType(Analysis_Data)

In [6]:
Analysis_Data.head()

,Time,Open,High,Low,Close,Volume,NumberOfTrades,BidVolume,AskVolume,RSI,UpPinBar,DownPinBar,TopType,BottomType,UpPregnantType,DownPregnantType,UpTriplePregnantType,DownTriplePregnantType,UpSwallowType,DownSwallowType
0,2019-01-02 08:30:00,22913.0,22998.0,22893.0,22993.0,17427.0,15543,8749,8678,NaN,0,0,0,0,0,0,0,0,0,0
1,2019-01-02 08:45:00,22994.0,23066.0,22992.0,23039.0,13398.0,11971,6484,6914,NaN,0,0,0,0,0,0,0,0,0,0
2,2019-01-02 09:00:00,23038.0,23173.0,22981.0,23155.0,13816.0,12027,7040,6776,NaN,0,0,0,0,0,0,0,0,0,0
3,2019-01-02 09:15:00,23157.0,23174.0,23087.0,23096.0,10712.0,9629,5457,5255,NaN,0,0,0,0,0,0,0,0,0,0
4,2019-01-02 09:45:00,23166.0,23224.0,23129.0,23189.0,10597.0,9088,5315,5282,NaN,0,0,0,0,0,0,0,0,0,0

In [7]:
# df = Analysis_Data.copy()
# df.Open.loc[1:3] = 1
# df.head()

In [8]:
UpPregnant = []
[UpPregnant.append(1) if (Analysis_Data.loc[i].UpPregnantType == 1) | (Analysis_Data.loc[i].UpTriplePregnantType == 1) else UpPregnant.append(0) for i in range(len(Analysis_Data))]
Analysis_Data['UpPregnant'] = UpPregnant

In [9]:
DownPregnant = []
[DownPregnant.append(1) if (Analysis_Data.loc[i].DownPregnantType == 1) | (Analysis_Data.loc[i].DownTriplePregnantType == 1) else DownPregnant.append(0) for i in range(len(Analysis_Data))]
Analysis_Data['DownPregnant'] = DownPregnant

In [13]:
# Analysis_Data.to_csv('./code_generated_csv/Analysis_Data.csv')

In [14]:
'''
要给之后的3根downpregnant，uppregnant赋上相同的值
要给之后的2根UpSwallowType，DownSwallowType赋上相同的值
之后的1根toptype和bottomtype赋上相同的值
'''

'\n要给之后的3根downpregnant，uppregnant赋上相同的值\n要给之后的2根UpSwallowType，DownSwallowType赋上相同的值\n之后的1根toptype和bottomtype赋上相同的值\n'

In [10]:
Analysis_deputy = Analysis_Data.copy()
for i in range(len(Analysis_deputy)):
    if Analysis_deputy.DownPregnant.loc[i] == 1:
        Analysis_Data.DownPregnant.loc[(i + 1) : (i + 3)] = 1
        i += 4

D:\anaconda\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [11]:
for i in range(len(Analysis_deputy)):
    if Analysis_deputy.UpSwallowType.loc[i] == 1:
        Analysis_Data.UpSwallowType.loc[(i + 1) :(i + 3)] = 1
        i += 4

In [12]:
for i in range(len(Analysis_deputy)):
    if Analysis_deputy.UpSwallowType.loc[i] == 1:
        Analysis_Data.UpSwallowType.loc[(i + 1) :(i + 2)] = 1
        i += 3

In [13]:
for i in range(len(Analysis_deputy)):
    if Analysis_deputy.DownSwallowType.loc[i] == 1:
        Analysis_Data.DownSwallowType.loc[(i + 1) :(i + 2)] = 1
        i += 3

In [14]:
for i in range(len(Analysis_deputy)):
    if Analysis_deputy.TopType.loc[i] == 1:
        Analysis_Data.TopType.loc[i + 1] = 1
        i += 2

In [15]:
for i in range(len(Analysis_deputy)):
    if Analysis_deputy.BottomType.loc[i] == 1:
        Analysis_Data.BottomType.loc[i + 1] = 1
        i += 2

In [21]:
# Analysis_Data.to_csv('./code_generated_csv/Analysis_Data1.csv')

In [ ]:
# def NewOpenBar(df):
    
#     summer = ((df.GMT < '2018-11-04 02:00:00') | \
#              ((df.GMT >= '2019-03-10 02:00:00') & (df.GMT < '2019-11-03 02:00:00')) | \
#              ((df.GMT >= '2020-03-08 02:00:00') & (df.GMT < '2020-11-01 02:00:00'))).values
    
#     df['SW'] = summer
#     df['DayOfWeek'] = df.GMT.dt.dayofweek
    
#     isOpenBar = []
    
#     for gmt, sw, dow in zip(df.GMT, df.SW, df.DayOfWeek):
        
#         if((sw == 1 and gmt.strftime('%H:%M:%S') == '13:30:00') or (sw == 0 and gmt.strftime('%H:%M:%S') == '14:30:00')):
            
#             if(dow != 5 and dow != 6):
            
#                 isOpenBar.append('Open')
            
#             else:
                
#                 isOpenBar.append(' ')
        
#         else:
            
#             isOpenBar.append(' ')
    
#     df['IsOpenBar'] = isOpenBar
    
#     date = []
#     for gmt in df.GMT:
#         date_temp = gmt.strftime("%Y-%m-%d")
#         date.append(date_temp)

#     df['Date'] = date
    
#     return df

In [ ]:
# df = NewOpenBar(df_c)

In [16]:
#往df中添加二次平滑的RSI
def AddRSI_T(df,T):
    '''
    由于RSI14是在index = 14时才有，故rsi2应该在index = 15开始才有意义，rsi7应该在index = 20时才有意义
    '''
    RSI_T = [0]* (T - 1 + 14)
    for i in range((T - 1 + 14),len(df)):
        RSI_T_sub = df[(i - T + 1) : (i + 1)].RSI.mean()
        RSI_T.append(RSI_T_sub)
    df['RSI_{}'.format(T)] = RSI_T

In [17]:
AddRSI_T(Analysis_Data,2)
AddRSI_T(Analysis_Data,7)

In [18]:
#给Analysis_Data增加previousRSI
Analysis_Data['previousRSI'] = [0] + Analysis_Data.RSI.values.tolist()[:-1]

In [19]:
Analysis_Data[:16]

,Time,Open,High,Low,Close,Volume,NumberOfTrades,BidVolume,AskVolume,RSI,...,DownPregnantType,UpTriplePregnantType,DownTriplePregnantType,UpSwallowType,DownSwallowType,UpPregnant,DownPregnant,RSI_2,RSI_7,previousRSI
0,2019-01-02 08:30:00,22913.0,22998.0,22893.0,22993.0,17427.0,15543,8749,8678,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,0.000000
1,2019-01-02 08:45:00,22994.0,23066.0,22992.0,23039.0,13398.0,11971,6484,6914,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
2,2019-01-02 09:00:00,23038.0,23173.0,22981.0,23155.0,13816.0,12027,7040,6776,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
3,2019-01-02 09:15:00,23157.0,23174.0,23087.0,23096.0,10712.0,9629,5457,5255,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
4,2019-01-02 09:45:00,23166.0,23224.0,23129.0,23189.0,10597.0,9088,5315,5282,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
5,2019-01-02 10:15:00,23268.0,23320.0,23231.0,23241.0,12992.0,11000,6704,6288,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
6,2019-01-02 10:30:00,23242.0,23291.0,23198.0,23282.0,10351.0,8995,5245,5106,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
7,2019-01-03 08:30:00,23106.0,23121.0,22956.0,22999.0,19021.0,17202,9465,9556,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
8,2019-01-03 08:45:00,23000.0,23008.0,22931.0,22998.0,11304.0,10107,5700,5604,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
9,2019-01-03 09:00:00,22997.0,22997.0,22762.0,22769.0,18691.0,16489,9763,8928,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
10,2019-01-03 09:15:00,22769.0,22838.0,22742.0,22795.0,15347.0,13375,7670,7677,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
11,2019-01-03 09:30:00,22793.0,22793.0,22644.0,22665.0,14495.0,12946,7540,6955,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
12,2019-01-03 09:45:00,22666.0,22764.0,22659.0,22757.0,11724.0,10536,5650,6074,NaN,...,0,0,0,0,0,0,0,0.000000,0.0,NaN
13,2019-01-03 10:00:00,22758.0,22812.0,22708.0,22788.0,11656.0,10389,5683,5973,NaN,...,0,1,0,0,0,1,0,0.000000,0.0,NaN
14,2019-01-03 10:15:00,22789.0,22837.0,22741.0,22747.0,10243.0,8816,4971,5272,40.080645,...,0,0,0,0,1,0,0,0.000000,0.0,NaN
15,2019-01-03 10:30:00,22746.0,22999.0,22729.0,22969.0,15675.0,13852,7444,8231,49.765966,...,0,0,0,1,1,0,0,44.923306,0.0,40.080645

In [20]:
def RSI_SMA_shortgodown(df,T):
    '''
        df为包含二次平滑完毕的RSI的表
        T为需要研究的区间长度，只要在T时间内有上穿或者下穿就认为有穿
    '''
        
    RSIShortgodown = []
    for i in range(len(df)):
        RSI_short = df.iloc[i:i + T +1,22].tolist()###这边要注意18是短期的平滑的rsi所在的位置，如果df表格不一样，这里需要修改
        RSI_long = df.iloc[i:i + T +1,23].tolist()
    
        #diff = RSI2 - RSI7#存在由正变负的就ok
        diff = [RSI_short[i] - RSI_long[i] for i in range(len(RSI_short))]
        #print(diff)
        for j in range(len(diff) - 1):
            #print(j)
            before_minus_after = diff[j] - diff[j + 1]
            rsi_short = RSI_short[j]
            rsi_long = RSI_long[j]
            #if (before_minus_after >= diff[j]) & (diff[j] >= 0) & (rsi_short >= 50) & (rsi_short <= 100)& (rsi_long >= 50) & (rsi_long <= 100):给rsi限定范围
            if (before_minus_after >= diff[j]) & (diff[j] >= 0):
                RSIShortgodown_sub = 1
                break
            else:
                RSIShortgodown_sub = 0
                continue
        RSIShortgodown.append(RSIShortgodown_sub)
    #print(len(RSIShortgodown))
    df['RSIShortgodown'] = RSIShortgodown

In [21]:
RSI_SMA_shortgodown(Analysis_Data,3)

In [ ]:
#"def RSI_SMA_shortgodown(df,T):\n",
 #   "    '''\n",
 #   "    相较于上面那个，增加了count变量，记录具体是在哪根穿越的\n",
 #   "    '''"

In [22]:
def RSI_SMA_shortgoup(df,T):
    '''
    df为包含二次平滑完毕的RSI的表
    T为需要研究的区间长度，只要在T时间内有上穿或者下穿就认为有穿
    '''
    RSIShortgoup = []
    for i in range(len(df)):
        RSI_short = df.iloc[i:i + T +1,22].tolist()###这边要注意18是短期的平滑的rsi所在的位置，如果df表格不一样，这里需要修改
        RSI_long = df.iloc[i:i + T +1,23].tolist()
        
        #diff = RSI2 - RSI7#存在由正变负的就ok\n",
        diff = [RSI_long[i] - RSI_short[i] for i in range(len(RSI_short))]
        #print(diff)\n",
        for j in range(len(diff) - 1):
            #print(j)\n",
            before_minus_after = diff[j] - diff[j + 1]
            rsi_short = RSI_short[j]
            rsi_long = RSI_long[j]
            #if (before_minus_after >= diff[j]) & (diff[j] >= 0) & (rsi_short >= 50) & (rsi_short <= 100)& (rsi_long >= 50) & (rsi_long <= 100):
            if (before_minus_after >= diff[j]) & (diff[j] >= 0):
                RSIShortgoup_sub = 1
                break
            else:
                RSIShortgoup_sub = 0
                continue
        RSIShortgoup.append(RSIShortgoup_sub)
    #print(len(RSIShortgodown))\n",
    df['RSIShortgoup'] = RSIShortgoup

In [23]:
RSI_SMA_shortgoup(Analysis_Data,3)

In [ ]:
# #给df增加一列开盘时间\n",
# df = pd.concat([df, pd.DataFrame(columns=['OpenTime'])], sort=False)
# opentimeIdx = df.loc[df.IsOpenBar == 'Open'].index
# for i,j in zip(opentimeIdx[:-1],opentimeIdx[1:]):
#     #df.OpenTime.iloc._setitem_with_indexer(df.loc[i:j].index, df.loc[i].GMT)\n",
#     df.OpenTime[(df.index >= i) & (df.index <= j-1)] = df.loc[i].GMT
# #最后一天的开盘时间手动加上\n",
# df.OpenTime[(df.index >= opentimeIdx[-1]) & (df.index < len(df))] = df.loc[opentimeIdx[-1]].GMT

In [25]:
#标记出极值点的index
import features.zigzag as fz
zig = fz.ZigZag(Analysis_Data,0.005)#为什么换了数据，就从原来的0.005变成了0.02
df_his_listed = zig.fixed_zzps(add_once=True)#历史被擦除的也显示了
df_only_last = zig.fixed_zzps()

In [26]:
df_his_listed

                      type_ bar_num  length  extremum
0     ZZPType.ONCE_HIGH_ZZP       1     0.0   23066.0
1     ZZPType.ONCE_HIGH_ZZP       2     0.0   23173.0
2     ZZPType.ONCE_HIGH_ZZP       3     0.0   23174.0
3     ZZPType.ONCE_HIGH_ZZP       4     0.0   23224.0
4     ZZPType.ONCE_HIGH_ZZP       5     0.0   23320.0
...                     ...     ...     ...       ...
1908  ZZPType.ONCE_HIGH_ZZP    1448     0.0   30132.0
1909       ZZPType.HIGH_ZZP    1448   491.0   30132.0
1910   ZZPType.ONCE_LOW_ZZP    1449     0.0   29989.0
1911        ZZPType.LOW_ZZP    1449  -143.0   29989.0
1912  ZZPType.ONCE_HIGH_ZZP    1450     0.0   30110.0

[1913 rows x 4 columns]

In [27]:
df_only_last.head(50)

               type_ bar_num  length  extremum
0   ZZPType.HIGH_ZZP       5   427.0   23320.0
1    ZZPType.LOW_ZZP      11  -676.0   22644.0
2   ZZPType.HIGH_ZZP      16   363.0   23007.0
3    ZZPType.LOW_ZZP      18  -392.0   22615.0
4   ZZPType.HIGH_ZZP      24   746.0   23361.0
5    ZZPType.LOW_ZZP      25  -138.0   23223.0
6   ZZPType.HIGH_ZZP      27   248.0   23471.0
7    ZZPType.LOW_ZZP      28  -150.0   23321.0
8   ZZPType.HIGH_ZZP      30   527.0   23848.0
9    ZZPType.LOW_ZZP      33  -290.0   23558.0
10  ZZPType.HIGH_ZZP      36   404.0   23962.0
11   ZZPType.LOW_ZZP      37  -190.0   23772.0
12  ZZPType.HIGH_ZZP      38   157.0   23929.0
13   ZZPType.LOW_ZZP      40  -236.0   23693.0
14  ZZPType.HIGH_ZZP      41   181.0   23874.0
15   ZZPType.LOW_ZZP      42  -141.0   23733.0
16  ZZPType.HIGH_ZZP      44   279.0   24012.0
17   ZZPType.LOW_ZZP      45  -152.0   23860.0
18  ZZPType.HIGH_ZZP      47   360.0   24220.0
19   ZZPType.LOW_ZZP      48  -152.0   24068.0
20  ZZPType.HIGH_ZZP      50   381.0   24449.0
21   ZZPType.LOW_ZZP      51  -208.0   24241.0
22  ZZPType.HIGH_ZZP      53   335.0   24576.0
23   ZZPType.LOW_ZZP      55  -347.0   24229.0
24  ZZPType.HIGH_ZZP      57   423.0   24652.0
25   ZZPType.LOW_ZZP      58  -376.0   24276.0
26  ZZPType.HIGH_ZZP      61   453.0   24729.0
27   ZZPType.LOW_ZZP      63  -422.0   24307.0
28  ZZPType.HIGH_ZZP      68   709.0   25016.0
29   ZZPType.LOW_ZZP      69  -220.0   24796.0
30  ZZPType.HIGH_ZZP      72   324.0   25120.0
31   ZZPType.LOW_ZZP      73  -169.0   24951.0
32  ZZPType.HIGH_ZZP      75   416.0   25367.0
33   ZZPType.LOW_ZZP      86  -465.0   24902.0
34  ZZPType.HIGH_ZZP      90   691.0   25593.0
35   ZZPType.LOW_ZZP      93  -289.0   25304.0
36  ZZPType.HIGH_ZZP     102   681.0   25985.0
37   ZZPType.LOW_ZZP     105  -172.0   25813.0
38  ZZPType.HIGH_ZZP     110   400.0   26213.0
39   ZZPType.LOW_ZZP     115  -341.0   25872.0
40  ZZPType.HIGH_ZZP     119   271.0   26143.0
41   ZZPType.LOW_ZZP     121  -157.0   25986.0
42  ZZPType.HIGH_ZZP     122   172.0   26158.0
43   ZZPType.LOW_ZZP     130  -540.0   25618.0
44  ZZPType.HIGH_ZZP     134   222.0   25840.0
45   ZZPType.LOW_ZZP     139  -502.0   25338.0
46  ZZPType.HIGH_ZZP     141   154.0   25492.0
47   ZZPType.LOW_ZZP     144  -241.0   25251.0
48  ZZPType.HIGH_ZZP     152   843.0   26094.0
49   ZZPType.LOW_ZZP     155  -394.0   25700.0

In [28]:
df_his_listed['High_or_Low'] = [str(df_his_listed.type_.loc[i]) for i in range(len(df_his_listed))]
df_only_last['High_or_Low'] = [str(df_only_last.type_.loc[i]) for i in range(len(df_only_last))]

In [29]:
extreme_bar_num = np.array(df_only_last.bar_num)

In [30]:
extreme_bar_num[(extreme_bar_num - 23) <= 0][-1]

18

In [ ]:
# df = df.dropna()

In [31]:
#填充BottomDivergence\n",
Analysis_Data = pd.concat([Analysis_Data, pd.DataFrame(columns=['BottomDivergence'])], sort=False)
def FillBottomDivergence(df):
    BottomDivergence = []
    for i in range(len(df)):
        current_time_index = i
        #print(i)
        #计算previous_extreme_time是哪根bar
        try:
            diff = extreme_bar_num - current_time_index#做差后寻找最后一个为负的 
            previous_extreme_time_index = extreme_bar_num[diff < 0][-1]#获取到上一个极值点的bar_num
        except:
            BottomDivergence.append(0)
            continue

        # 获取当前的RSI和Low
        current_RSI = df.loc[current_time_index].RSI
        current_Low = df.loc[current_time_index].Low


        # 获取上一个极值点到当前的这段区间的RSI和Low
        df_period = df[(df.index >= previous_extreme_time_index) & (df.index < current_time_index)]
        period_extreme_Low = df_period.Low.min()
        period_extreme_Low_index = df_period[df_period.Low == period_extreme_Low].index[0]
        period_extreme_RSI = df.loc[period_extreme_Low_index].RSI
        
        
        
        if (current_Low < period_extreme_Low) & (current_RSI > period_extreme_RSI):
            BottomDivergence_sub = 1
            
        else:
            BottomDivergence_sub = 0
            
        BottomDivergence.append(BottomDivergence_sub)
    df['BottomDivergence'] = BottomDivergence

In [32]:
FillBottomDivergence(Analysis_Data)

In [33]:
Analysis_Data.tail()

,Time,Open,High,Low,Close,Volume,NumberOfTrades,BidVolume,AskVolume,RSI,...,UpSwallowType,DownSwallowType,UpPregnant,DownPregnant,RSI_2,RSI_7,previousRSI,RSIShortgodown,RSIShortgoup,BottomDivergence
1446,2020-12-21 09:15:00,29738.0,29746.0,29641.0,29701.0,11384.0,10592.0,5654.0,5730.0,54.627529,...,0.0,0.0,0.0,0.0,55.061759,60.189917,55.495988,0.0,1.0,0
1447,2020-12-21 09:30:00,29701.0,29771.0,29662.0,29759.0,10302.0,9707.0,5360.0,4942.0,55.765364,...,0.0,0.0,0.0,0.0,55.196447,58.772001,54.627529,0.0,1.0,0
1448,2020-12-21 14:45:00,30055.0,30132.0,30007.0,30104.0,10740.0,9639.0,5588.0,5152.0,61.887830,...,0.0,0.0,0.0,0.0,58.826597,58.480259,55.765364,0.0,0.0,0
1449,2020-12-22 08:30:00,30075.0,30082.0,29989.0,30004.0,11131.0,9961.0,5766.0,5365.0,59.324732,...,0.0,0.0,0.0,0.0,60.606281,58.550203,61.887830,0.0,0.0,0
1450,2020-12-23 08:30:00,30026.0,30110.0,30022.0,30089.0,10285.0,9207.0,4990.0,5295.0,60.810442,...,0.0,0.0,0.0,0.0,60.067587,58.106395,59.324732,0.0,0.0,0

In [ ]:
# #填充BottomDivergence\n",
# Analysis_Data = pd.concat([Analysis_Data, pd.DataFrame(columns=['BottomDivergence'])], sort=False)
# def FillBottomDivergence(df):
#     BottomDivergence = []
#     for i in range(62,len(df)+ 62):
#         current_time = df.loc[i].GMT
#         #计算previous_extreme_time是哪根bar
#         diff = extreme_bar_num - current_time#做差后寻找最后一个为负的 
#         previous_extreme_time = extreme_bar_num[diff < 0][-1]#获取到上一个极值点的bar_num
        
#         K_low = df[(df.GMT >= open_time) & (df.GMT < current_time)].Low.min()
        
#         RSI_low = df[(df.GMT >= open_time) & (df.GMT < current_time)].RSI.min()
        
#         K_current = df.loc[i].Low
        
#         RSI_current = df.loc[i].RSI
        
#         if (K_current < K_low) & (RSI_current > RSI_low):
#             BottomDivergence_sub = 1
            
#         else:
#             BottomDivergence_sub = 0
            
#         BottomDivergence.append(BottomDivergence_sub)
#     df['BottomDivergence'] = BottomDivergence

In [48]:
Analysis_Data[Analysis_Data.BottomDivergence == 1]

,Time,Open,High,Low,Close,Volume,NumberOfTrades,BidVolume,AskVolume,RSI,...,UpSwallowType,DownSwallowType,UpPregnant,DownPregnant,RSI_2,RSI_7,previousRSI,RSIShortgodown,RSIShortgoup,BottomDivergence
15,2016-01-20 08:30:00,15652.0,15880.0,15365.0,15700.0,395245.0,303281.0,199358.0,195887.0,23.833678,...,0.0,1.0,0.0,0.0,23.057048,0.000000,22.280419,0,0.0,1
27,2016-02-03 08:30:00,16174.0,16370.0,15875.0,16218.0,360136.0,273772.0,183003.0,177133.0,43.769835,...,0.0,0.0,0.0,1.0,43.039556,41.975136,42.309278,1,0.0,1
33,2016-02-10 08:30:00,16026.0,16154.0,15505.0,15607.0,294203.0,224941.0,148157.0,146046.0,34.752660,...,1.0,1.0,0.0,0.0,38.694867,40.333698,42.637075,0,1.0,1
34,2016-02-11 08:30:00,15608.0,15791.0,15452.0,15740.0,321902.0,248891.0,162221.0,159681.0,38.640631,...,1.0,1.0,0.0,0.0,36.696645,39.600955,34.752660,0,1.0,1
45,2016-02-24 08:30:00,16254.0,16543.0,16131.0,16487.0,196441.0,154703.0,97622.0,98819.0,55.035403,...,0.0,0.0,0.0,0.0,52.388527,54.567298,49.741652,1,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,2020-11-19 08:30:00,29307.0,29474.0,29144.0,29382.0,151207.0,133608.0,76221.0,74986.0,58.565619,...,0.0,1.0,0.0,1.0,58.209558,62.146799,57.853498,0,1.0,1
1522,2020-11-26 08:30:00,29825.0,29926.0,29696.0,29897.0,35233.0,32033.0,17320.0,17913.0,62.120738,...,0.0,0.0,0.0,0.0,61.754914,60.237518,61.389089,1,0.0,1
1525,2020-11-30 08:30:00,29702.0,29995.0,29428.0,29934.0,167355.0,150925.0,83519.0,83836.0,61.401640,...,0.0,0.0,0.0,0.0,59.988264,61.625274,58.574887,0,1.0,1
1527,2020-12-02 08:30:00,29664.0,29941.0,29589.0,29891.0,136772.0,123994.0,68070.0,68702.0,59.467688,...,0.0,0.0,0.0,0.0,58.033681,60.223930,56.599673,0,1.0,1
1546,2020-12-24 08:30:00,30060.0,30118.0,29997.0,30102.0,30235.0,26875.0,15899.0,14336.0,55.005203,...,0.0,0.0,0.0,1.0,54.595229,55.115647,54.185255,0,0.0,1

In [34]:
#填充TopDivergence\n",
Analysis_Data = pd.concat([Analysis_Data, pd.DataFrame(columns=['TopDivergence'])], sort=False)
def FillTopDivergence(df):
    TopDivergence = []
    for i in range(len(df)):
        current_time_index = i
        #print(i)
        #计算previous_extreme_time是哪根bar
        try:
            diff = extreme_bar_num - current_time_index#做差后寻找最后一个为负的 
            previous_extreme_time_index = extreme_bar_num[diff < 0][-1]#获取到上一个极值点的bar_num
        except:
            TopDivergence.append(0)
            continue

        # 获取当前的RSI和Low
        current_RSI = df.loc[current_time_index].RSI
        current_High = df.loc[current_time_index].High


        # 获取上一个极值点到当前的这段区间的RSI和Low
        df_period = df[(df.index >= previous_extreme_time_index) & (df.index < current_time_index)]
        period_extreme_High = df_period.High.max()
        period_extreme_High_index = df_period[df_period.High == period_extreme_High].index[0]
        period_extreme_RSI = df.loc[period_extreme_High_index].RSI
        
        
        
        if (current_High > period_extreme_High) & (current_RSI < period_extreme_RSI):
            TopDivergence_sub = 1
            
        else:
            TopDivergence_sub = 0
            
        TopDivergence.append(TopDivergence_sub)
    df['TopDivergence'] = TopDivergence

In [35]:
FillTopDivergence(Analysis_Data)

In [51]:
Analysis_Data[Analysis_Data.TopDivergence == 1]

,Time,Open,High,Low,Close,Volume,NumberOfTrades,BidVolume,AskVolume,RSI,...,DownSwallowType,UpPregnant,DownPregnant,RSI_2,RSI_7,previousRSI,RSIShortgodown,RSIShortgoup,BottomDivergence,TopDivergence
17,2016-01-22 08:30:00,16013.0,16052.0,15890.0,16005.0,137505.0,103374.0,68377.0,69128.0,33.267378,...,0.0,0.0,0.0,33.324775,0.000000,33.382173,0.0,0.0,0.0,1
21,2016-01-27 08:30:00,15989.0,16151.0,15768.0,15985.0,288411.0,226915.0,145609.0,142802.0,34.891777,...,0.0,0.0,0.0,34.945776,32.072299,34.999775,0.0,0.0,0.0,1
24,2016-01-31 08:30:00,16367.0,16378.0,16228.0,16275.0,51931.0,42140.0,26152.0,25779.0,44.628076,...,0.0,0.0,0.0,45.762023,37.748778,46.895969,0.0,0.0,0.0,1
25,2016-02-01 08:30:00,16275.0,16426.0,16168.0,16188.0,170511.0,133966.0,85032.0,85479.0,42.636484,...,0.0,1.0,1.0,43.632280,39.156594,44.628076,0.0,0.0,0.0,1
33,2016-02-10 08:30:00,16026.0,16154.0,15505.0,15607.0,294203.0,224941.0,148157.0,146046.0,34.752660,...,1.0,0.0,0.0,38.694867,40.333698,42.637075,0.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,2020-11-30 08:30:00,29702.0,29995.0,29428.0,29934.0,167355.0,150925.0,83519.0,83836.0,61.401640,...,0.0,0.0,0.0,59.988264,61.625274,58.574887,0.0,1.0,1.0,1
1526,2020-12-01 08:30:00,29933.0,30057.0,29606.0,29665.0,162805.0,149115.0,81546.0,81259.0,56.599673,...,0.0,1.0,0.0,59.000657,60.782008,61.401640,0.0,1.0,0.0,1
1530,2020-12-06 08:30:00,30220.0,30263.0,29992.0,30128.0,44904.0,40515.0,22593.0,22311.0,62.214392,...,0.0,0.0,0.0,62.392732,60.275191,62.571073,1.0,0.0,0.0,1
1533,2020-12-09 08:30:00,30268.0,30309.0,29919.0,29942.0,190093.0,174029.0,96723.0,93370.0,56.322655,...,0.0,0.0,0.0,59.582498,60.444458,62.842342,0.0,0.0,0.0,1
1537,2020-12-14 08:30:00,30159.0,30240.0,29751.0,29952.0,140395.0,131214.0,70027.0,70368.0,54.996159,...,0.0,0.0,0.0,57.037252,57.354604,59.078345,0.0,1.0,0.0,1

In [ ]:
# #填充TopDivergence\n",
# df = pd.concat([df, pd.DataFrame(columns=['TopDivergence'])], sort=False)
# TopDivergence = []
# for i in range(62,len(df) + 62):
#     current_time = df.loc[i].GMT
#     open_time = df.loc[i].OpenTime
    
#     K_high = df[(df.GMT >= open_time) & (df.GMT < current_time)].High.max()
    
#     RSI_high = df[(df.GMT >= open_time) & (df.GMT < current_time)].RSI.max()
    
#     K_current = df.loc[i].High
    
#     RSI_current = df.loc[i].RSI
    
#     if (K_current > K_high) & (RSI_current < RSI_high):
#         TopDivergence_sub = 1
        
#     else:
#         TopDivergence_sub = 0
        
#     TopDivergence.append(TopDivergence_sub)
# df['TopDivergence'] = TopDivergence

In [ ]:
# df[df.TopDivergence == 1]

In [ ]:
# #BottomType TopType 要往上提一位[1:]UpPregnantType DownPregnantType要往上提两位[2:]\n",
# df['BottomType'] = df.BottomType.iloc[1:].tolist() + [0]
# df['TopType'] = df.TopType.iloc[1:].tolist() + [0]
# df['UpPregnantType'] = df.UpPregnantType.iloc[2:].tolist() + [0]*2
# df['DownPregnantType'] = df.DownPregnantType.iloc[2:].tolist() + [0]*2

In [ ]:
#df = pd.concat([df, pd.DataFrame(columns=['Y'])], sort=False)\n",
    #for i in range(len(df1)):\n",
    #    if df1.loc[i].High_or_Low == 'ZZPType.HIGH_ZZP':\n",
    #        df.Y.loc[df1.loc[i].bar_num] = -1\n",
    #    else:\n",
    #        df.Y.loc[df1.loc[i].bar_num] = 1"

In [ ]:
#df.to_csv('df.csv')

In [ ]:
df[:16]

In [36]:
def CompareCurrentRSIwithyes(df):
    df['currentRSI_lessthan_lastRSI'] = [1 if df.iloc[i].RSI < df.iloc[i].previousRSI else 0 for i in range(len(df))]
    df['currentRSI_morethan_lastRSI'] = [1 if df.iloc[i].RSI > df.iloc[i].previousRSI else 0 for i in range(len(df))]

In [37]:
CompareCurrentRSIwithyes(Analysis_Data)

In [38]:
Analysis_Data.to_csv('./code_generated_csv/previous_Analysis_Data.csv')

In [ ]:
# df_his_listed = zig.fixed_zzps(add_once=True)#历史被擦除的也显示了
# df_only_last = zig.fixed_zzps()

In [63]:
df_only_last.head(10)

              type_ bar_num  length  extremum       High_or_Low
0   ZZPType.LOW_ZZP       6 -1309.0   16085.0   ZZPType.LOW_ZZP
1  ZZPType.HIGH_ZZP       8   448.0   16533.0  ZZPType.HIGH_ZZP
2   ZZPType.LOW_ZZP      11  -785.0   15748.0   ZZPType.LOW_ZZP
3  ZZPType.HIGH_ZZP      13   440.0   16188.0  ZZPType.HIGH_ZZP
4   ZZPType.LOW_ZZP      15  -823.0   15365.0   ZZPType.LOW_ZZP
5  ZZPType.HIGH_ZZP      17   687.0   16052.0  ZZPType.HIGH_ZZP
6   ZZPType.LOW_ZZP      19  -412.0   15640.0   ZZPType.LOW_ZZP
7  ZZPType.HIGH_ZZP      21   511.0   16151.0  ZZPType.HIGH_ZZP
8   ZZPType.LOW_ZZP      22  -376.0   15775.0   ZZPType.LOW_ZZP
9  ZZPType.HIGH_ZZP      25   651.0   16426.0  ZZPType.HIGH_ZZP

In [64]:
#算Ratio1
#获取了有出现两次的bar，也即这个bar_num为最终未被擦除的\n",
def AddRatio1(df1,df2):

    high_or_low_barnum = df1[abs(df1.length) >1e-6].bar_num.tolist()
    # high_or_low_barnum
    # startNum = high_or_low_barnum[:-1] 
    # endNum = high_or_low_barnum[1:]
    startNum = high_or_low_barnum[:]
    endNum = high_or_low_barnum[1:] + [len(df1)]
    ratio1 = []
    for num in df1.bar_num.tolist():
        if num >= 22:#保证df2中有足够的8个数值可以计算\n", 445
            #print(num)
            flag = 1
            for i,j in zip(startNum,endNum):
                if flag:
                    if (num == i) | (num == j):
                        Idx = df2[df2.bar_num == num].index[0]
                        #print(Idx)
                        last5 = []
                        count = 0
                        while count <= 4:
                            last5.append(abs(df2.loc[Idx - 2*count].length))
                            count += 1
                        last5_mean = np.mean(last5)
                        last5_std = np.std(last5)
                        ratio1_sub = (abs(df2.loc[Idx].length) - last5_mean)/last5_std
                        ratio1.append(ratio1_sub)
                        flag = 0
                    elif (num > i) & (num < j):
                        Idx = df2[df2.bar_num == i].index[0]
                        current_Idx = df1[df1.bar_num == num].index[0]
                        first_last5 = abs(df2.loc[Idx].extremum - df1.loc[current_Idx].extremum)
                        last5 = [first_last5]
                        count = 0
                        while count <= 3:
                            last5.append(abs(df2.loc[Idx - 2*count].length))
                            count += 1
                        last5_mean = np.mean(last5)
                        last5_std = np.std(last5)
                        ratio1_sub = (first_last5 - last5_mean)/last5_std
                        ratio1.append(ratio1_sub)
                        flag = 0
                    else:
                        #print(i)
                        continue
        else:
            ratio1.append(0)
            continue
    df1['ratio1'] = ratio1
    print(len(ratio1))
    print(len(df1.bar_num.tolist()))

In [65]:
AddRatio1(df_his_listed,df_only_last)

2151
2151

In [66]:
df_his_listed

,type_,bar_num,length,extremum,High_or_Low,ratio1
0,ZZPType.ONCE_LOW_ZZP,0,0.0,16995.0,ZZPType.ONCE_LOW_ZZP,0.000000
1,ZZPType.ONCE_LOW_ZZP,1,0.0,16860.0,ZZPType.ONCE_LOW_ZZP,0.000000
2,ZZPType.ONCE_LOW_ZZP,2,0.0,16753.0,ZZPType.ONCE_LOW_ZZP,0.000000
3,ZZPType.ONCE_LOW_ZZP,3,0.0,16391.0,ZZPType.ONCE_LOW_ZZP,0.000000
4,ZZPType.ONCE_LOW_ZZP,4,0.0,16367.0,ZZPType.ONCE_LOW_ZZP,0.000000
...,...,...,...,...,...,...
2146,ZZPType.ONCE_LOW_ZZP,1544,0.0,29735.0,ZZPType.ONCE_LOW_ZZP,-0.599062
2147,ZZPType.LOW_ZZP,1544,-463.0,29735.0,ZZPType.LOW_ZZP,-0.599062
2148,ZZPType.ONCE_HIGH_ZZP,1545,0.0,30182.0,ZZPType.ONCE_HIGH_ZZP,-0.768153
2149,ZZPType.HIGH_ZZP,1545,447.0,30182.0,ZZPType.HIGH_ZZP,-0.768153
2150,ZZPType.ONCE_LOW_ZZP,1546,0.0,29997.0,ZZPType.ONCE_LOW_ZZP,-1.469357

In [67]:
#算Ratio2
#获取了有出现两次的bar，也即这个bar_num为最终未被擦除的\n",
def AddRatio2(df1,df2):
    high_or_low_barnum = df1[abs(df1.length) >1e-6].bar_num.tolist()
    high_or_low_barnum
    # startNum = high_or_low_barnum[:-1]
    # endNum = high_or_low_barnum[1:]
    startNum = high_or_low_barnum[:]
    endNum = high_or_low_barnum[1:] + [len(df1)]
    ratio2 = []
    for num in df1.bar_num.tolist():
        if num >= 22:#保证df2中有足够的8个数值可以计算\n", 445
            #print(num)
            flag = 1
            for i,j in zip(startNum,endNum):
                if flag:
                    if (num == i) | (num == j):
                        Idx = df2[df2.bar_num == num].index[0]
                        #print(Idx)
                        last9 = []
                        count = 0
                        while count <= 8:
                            last9.append(abs(df2.loc[Idx - count].length))
                            count += 1
                        last9_mean = np.mean(last9)
                        last9_std = np.std(last9)
                        ratio2_sub = (abs(df2.loc[Idx].length) - last9_mean)/last9_std
                        ratio2.append(ratio2_sub)
                        flag = 0
                    elif (num > i) & (num < j):
                        Idx = df2[df2.bar_num == i].index[0]
                        current_Idx = df1[df1.bar_num == num].index[0]
                        first_last9 = abs(df2.loc[Idx].extremum - df1.loc[current_Idx].extremum)
                        last9 = [first_last9]
                        count = 0
                        while count <= 7:
                            last9.append(abs(df2.loc[Idx - count].length))
                            count += 1
                        last9_mean = np.mean(last9)
                        last9_std = np.std(last9)
                        ratio2_sub = (first_last9 - last9_mean)/last9_std
                        ratio2.append(ratio2_sub)
                        flag = 0
                    else:
                        #print(i)
                        continue
        else:
            ratio2.append(0)
            continue
    df1['ratio2'] = ratio2
    print(len(ratio2))
    print(len(df1.bar_num.tolist()))

In [68]:
AddRatio2(df_his_listed,df_only_last)

2151
2151

In [69]:
df_his_listed

,type_,bar_num,length,extremum,High_or_Low,ratio1,ratio2
0,ZZPType.ONCE_LOW_ZZP,0,0.0,16995.0,ZZPType.ONCE_LOW_ZZP,0.000000,0.000000
1,ZZPType.ONCE_LOW_ZZP,1,0.0,16860.0,ZZPType.ONCE_LOW_ZZP,0.000000,0.000000
2,ZZPType.ONCE_LOW_ZZP,2,0.0,16753.0,ZZPType.ONCE_LOW_ZZP,0.000000,0.000000
3,ZZPType.ONCE_LOW_ZZP,3,0.0,16391.0,ZZPType.ONCE_LOW_ZZP,0.000000,0.000000
4,ZZPType.ONCE_LOW_ZZP,4,0.0,16367.0,ZZPType.ONCE_LOW_ZZP,0.000000,0.000000
...,...,...,...,...,...,...,...
2146,ZZPType.ONCE_LOW_ZZP,1544,0.0,29735.0,ZZPType.ONCE_LOW_ZZP,-0.599062,-0.687444
2147,ZZPType.LOW_ZZP,1544,-463.0,29735.0,ZZPType.LOW_ZZP,-0.599062,-0.687444
2148,ZZPType.ONCE_HIGH_ZZP,1545,0.0,30182.0,ZZPType.ONCE_HIGH_ZZP,-0.768153,-0.804680
2149,ZZPType.HIGH_ZZP,1545,447.0,30182.0,ZZPType.HIGH_ZZP,-0.768153,-0.804680
2150,ZZPType.ONCE_LOW_ZZP,1546,0.0,29997.0,ZZPType.ONCE_LOW_ZZP,-1.469357,-1.681938

In [70]:
df_his_listed.to_csv('./code_generated_csv/df_his_listed.csv')

In [ ]:
# df.to_csv('df.csv')

In [ ]:
# ratio1 = [0] * 8#先拿8个0占位\n",
# for i in range(8,len(df2)):
#     #print(i)\n",
#     last5 = []
#     count = 0
#     while count <= 4:
#         last5.append(abs(df2.loc[i - 2*count].length))
#         count += 1
#     last5_mean = np.mean(last5)
#     last5_std = np.std(last5)
#     ratio1_sub = (abs(df2.loc[i].length) - last5_mean)/last5_std
#     ratio1.append(ratio1_sub)
# ratio1
# df2['last5'] =  ratio1

In [ ]:
# ratio2 = [0] * 8#先拿8个0占位\n",
# for i in range(8,len(df2)):
#     #print(i)\n",
#     last9 = []
#     count = 0
#     while count <= 8:
#         last9.append(abs(df2.loc[i - count].length))
#         count += 1
#     last9_mean = np.mean(last9)
#     last9_std = np.std(last9)
#     ratio2_sub = (abs(df2.loc[i].length) - last9_mean)/last9_std
#     ratio2.append(ratio2_sub)
    
# ratio2
# df2['last9'] =  ratio2

In [ ]:
# df_short = df[df.Y == -1].reset_index(drop = True)
# df_short[:3]

In [ ]:
# findIdx = pd.read_csv('findIdx.csv')
# findIdx[:3]

In [ ]:
#给findIdx增加每日的range，用highest-lowest\n",
# findIdx['Range'] = findIdx.highest - findIdx.lowest

In [ ]:
"#计算分子Numerator\n",
    "Numerator_short = []\n",
    "for i in range(len(df_short)):\n",
    "    Day = df_short.loc[i].Date\n",
    "    #print(Day)\n",
    "    if findIdx[findIdx.Date == Day].values.tolist() == []:\n",
    "        Numerator_sub = 0\n",
    "        Numerator_short.append(Numerator_sub)\n",
    "        continue\n",
    "    else:\n",
    "    \n",
    "        Hightime = pd.to_datetime(findIdx[findIdx.Date == Day].highest_time.values[0])\n",
    "        #print(Hightime)\n",
    "        highest = findIdx[findIdx.Date == Day].highest.values[0]\n",
    "        #print(highest)\n",
    "        Lowtime = pd.to_datetime(findIdx[findIdx.Date == Day].lowest_time.values[0])\n",
    "        #print(Lowtime)\n",
    "        lowest = findIdx[findIdx.Date == Day].lowest.values[0]\n",
    "        #print(lowest)\n",
    "        Openprice = findIdx[findIdx.Date == Day].open_price.values[0]\n",
    "        Currenttime = df_short.loc[i].GMT\n",
    "        #print(Currenttime)\n",
    "        CurrentHigh = df_short.loc[i].High\n",
    "        #print(CurrentHigh)\n",
    "        if Hightime <= Lowtime:\n",
    "            if Currenttime <= Hightime:\n",
    "                Numerator_sub = CurrentHigh - Openprice\n",
    "            elif Currenttime >= Lowtime:\n",
    "                Numerator_sub = highest - lowest\n",
    "            else:\n",
    "                Numerator_sub = highest - Openprice\n",
    "        else:\n",
    "\n",
    "            if Currenttime <= Lowtime:\n",
    "                Numerator_sub = CurrentHigh - Openprice\n",
    "            elif Currenttime >= Hightime:\n",
    "                Numerator_sub = highest - lowest\n",
    "            else:\n",
    "                Numerator_sub = CurrentHigh - lowest\n",
    "        Numerator_short.append(Numerator_sub)    \n",
    "df_short['Numerator'] = Numerator_short

In [ ]:
"#给df_short增加yesterday range\n",
    "YesterdayRange_short = []\n",
    "for i in range(len(df_short)):\n",
    "    Day = df_short.loc[i].Date\n",
    "    #print(Day)\n",
    "    if findIdx[findIdx.Date == Day].values.tolist() == []:\n",
    "        Range_sub = 0\n",
    "        YesterdayRange_short.append(Range_sub)\n",
    "        continue\n",
    "    else:\n",
    "        yesterdayIdx = findIdx[findIdx.Date == Day].index[0] - 1\n",
    "        Range_sub = findIdx.loc[yesterdayIdx].Range\n",
    "        YesterdayRange_short.append(Range_sub)\n",
    "df_short['YesterdayRange'] = YesterdayRange_short"

In [ ]:
"df_short['Ratio'] = df_short.Numerator/df_short.YesterdayRange"
"df_short_cleaned = df_short[(df_short.Numerator > epsilon) & (df_short.YesterdayRange > epsilon)]"

In [ ]:
"df_long = df[df.Y == 1].reset_index(drop = True)\n",
    "df_long[:3]"

In [ ]:
"#计算分子Numerator\n",
    "Numerator_long = []\n",
    "for i in range(len(df_long)):\n",
    "    Day = df_long.loc[i].Date\n",
    "    #print(Day)\n",
    "    if findIdx[findIdx.Date == Day].values.tolist() == []:\n",
    "        Numerator_sub = 0\n",
    "        Numerator_long.append(Numerator_sub)\n",
    "        continue\n",
    "    else:\n",
    "    \n",
    "        Hightime = pd.to_datetime(findIdx[findIdx.Date == Day].highest_time.values[0])\n",
    "        #print(Hightime)\n",
    "        highest = findIdx[findIdx.Date == Day].highest.values[0]\n",
    "        #print(highest)\n",
    "        Lowtime = pd.to_datetime(findIdx[findIdx.Date == Day].lowest_time.values[0])\n",
    "        #print(Lowtime)\n",
    "        lowest = findIdx[findIdx.Date == Day].lowest.values[0]\n",
    "        #print(lowest)\n",
    "        Openprice = findIdx[findIdx.Date == Day].open_price.values[0]\n",
    "        Currenttime = df_long.loc[i].GMT\n",
    "        #print(Currenttime)\n",
    "        CurrentLow = df_long.loc[i].Low\n",
    "        #print(CurrentHigh)\n",
    "        if Hightime <= Lowtime:\n",
    "            if Currenttime <= Hightime:\n",
    "                Numerator_sub =  Openprice - CurrentLow\n",
    "            elif Currenttime >= Lowtime:\n",
    "                Numerator_sub = highest - lowest\n",
    "            else:\n",
    "                Numerator_sub = highest - CurrentLow\n",
    "        else:\n",
    "\n",
    "            if Currenttime <= Lowtime:\n",
    "                Numerator_sub =  Openprice - CurrentLow\n",
    "            elif Currenttime >= Hightime:\n",
    "                Numerator_sub = highest - lowest\n",
    "            else:\n",
    "                Numerator_sub = Openprice - lowest\n",
    "        Numerator_long.append(Numerator_sub)    \n",
    "df_long['Numerator'] = Numerator_long

In [ ]:
"#给df_long增加yesterday range\n",
    "YesterdayRange_long = []\n",
    "for i in range(len(df_long)):\n",
    "    Day = df_long.loc[i].Date\n",
    "    #print(Day)\n",
    "    if findIdx[findIdx.Date == Day].values.tolist() == []:\n",
    "        Range_sub = 0\n",
    "        YesterdayRange_long.append(Range_sub)\n",
    "        continue\n",
    "    else:\n",
    "        yesterdayIdx = findIdx[findIdx.Date == Day].index[0] - 1\n",
    "        Range_sub = findIdx.loc[yesterdayIdx].Range\n",
    "        YesterdayRange_long.append(Range_sub)\n",
    "df_long['YesterdayRange'] = YesterdayRange_long"

In [ ]:
"df_long['Ratio'] = df_long.Numerator/df_long.YesterdayRange"
"df_long_cleaned = df_long[(df_long.Numerator > epsilon) & (df_long.YesterdayRange > epsilon)]"

In [ ]:
"df_all = pd.concat([df_short_cleaned,df_long_cleaned])"

In [ ]:
"df_all.to_csv('df_all_regression.csv')"